version: '3.8'

services:
  prosody:
    image: prosody/prosody
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
    volumes:
      # - ./data:/var/lib/prosody
      - ./log:/var/log/prosody

      - ./src/config:/etc/prosody:ro
